version: "3.9"
services:
  app:
    build: .
    environment:
      DB_HOST: db
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    working_dir: /app
    command:
      - "sh"
      - "-c"
      - "python -m api"
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agno
      - PGDATA=/var/lib/postgresql/data/pgdata